apiVersion: v1
kind: Pod
metadata:
  name: docker-image-build
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
  - name: dind
    image: docker:23.0.6-dind
    imagePullPolicy: Always
    securityContext:
      privileged: true
